---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# lambdapply

<!-- badges: start -->
<!-- badges: end -->

The goal of `lambdapply` is to enable R users to scale their R code using [AWS Lambda serverless compute service](https://aws.amazon.com/lambda/), with a familiar *apply syntax.  Running 
arbitrary code in AWS Lambda has [limitations](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html), and so this package is intended to aid in running code that is _iterable_. Each iteration needs to be:

* Independent
* Short-running
* Computing across a _small_ piece of data

Code those does not meet this criteria will not benefit from scaling horizontally with AWS lambda. The idea
for this package was born from needing to perform many mutually exclusive function optimisations at once. Each iteration of the optimisation would only take one minute to complete, but when executing across many iterations in sequence, the end-user can wait hours for a result. With this approach, each iteration can be performed _at the same time_ using serverless compute.

## Installation

You can install the development version of lambdapply from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("liamgilbey/lambdapply")
```
